project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  sidebar:
    contents:
      - text: Home
        href: index.qmd
      - finalproject.qmd
      
format:
  html:
    backgroundcolor: "lightpink"
    linkcolor: "hotpink"
    mainfont: "mono"
    theme: [cosmo, styles.scss]