project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - Obesity-Final-Project.qmd

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    background: "pink"
    left:
      - text: Home
        href: index.qmd
      - Obesity-Final-Project.qmd
      
format:
  html:
    backgroundcolor: "White"
    linkcolor: "hotpink"
    mainfont: "mono"
    theme: [cosmo, styles.scss]