project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - Obesity-Final-Project.qmd

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    background: "#e6e6fa"
    title: Kaelyn Marquez
    left:
      - href: Obesity-Final-Project.qmd
        text: Final Project
      
format:
  html:
    backgroundcolor: "lavenderblush"
    linkcolor: "deeppink"
    mainfont: "Atkinson Hyperlegible"
    theme: [flatly, styles.scss]
    toc: true
    toc-location: left
    toc-depth: 2
    